spring:
  datasource:
    url: jdbc:h2:~/test;AUTO_SERVER=TRUE;MODE=MYSQL;DATABASE_TO_UPPER=true
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    properties.hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      use_sql_comments: true
      format_sql: true
    show_sql: true
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: true